// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	//CreateTodo
	//
	//  INSERT INTO todos (user_id, title, description)
	//  VALUES ($1, $2, $3)
	//  RETURNING id, user_id, title, description, completed, created_at, updated_at
	CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error)
	//CreateUser
	//
	//  INSERT INTO users (email, name, avatar_url, provider, provider_id)
	//  VALUES ($1, $2, $3, $4, $5)
	//  RETURNING id, email, name, avatar_url, provider, provider_id, created_at, updated_at
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	//DeleteTodo
	//
	//  DELETE FROM todos
	//  WHERE id = $1 AND user_id = $2
	DeleteTodo(ctx context.Context, arg DeleteTodoParams) error
	//GetTodoByID
	//
	//  SELECT id, user_id, title, description, completed, created_at, updated_at FROM todos
	//  WHERE id = $1 AND user_id = $2
	GetTodoByID(ctx context.Context, arg GetTodoByIDParams) (Todo, error)
	//GetUserByID
	//
	//  SELECT id, email, name, avatar_url, provider, provider_id, created_at, updated_at FROM users WHERE id = $1
	GetUserByID(ctx context.Context, id int64) (User, error)
	//GetUserByProviderID
	//
	//  SELECT id, email, name, avatar_url, provider, provider_id, created_at, updated_at FROM users
	//  WHERE provider = $1 AND provider_id = $2
	GetUserByProviderID(ctx context.Context, arg GetUserByProviderIDParams) (User, error)
	//ListTodosByUser
	//
	//  SELECT id, user_id, title, description, completed, created_at, updated_at FROM todos
	//  WHERE user_id = $1
	//  ORDER BY created_at DESC
	ListTodosByUser(ctx context.Context, userID int64) ([]Todo, error)
	//UpdateTodo
	//
	//  UPDATE todos
	//  SET
	//      title = COALESCE($3, title),
	//      description = COALESCE($4, description),
	//      completed = COALESCE($5, completed),
	//      updated_at = NOW()
	//  WHERE id = $1 AND user_id = $2
	//  RETURNING id, user_id, title, description, completed, created_at, updated_at
	UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error)
	//UpdateUser
	//
	//  UPDATE users
	//  SET
	//      name = $2,
	//      avatar_url = $3,
	//      updated_at = NOW()
	//  WHERE id = $1
	//  RETURNING id, email, name, avatar_url, provider, provider_id, created_at, updated_at
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
