// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sqlc "go-todo/db/sqlc"
)

// MockTodoRepository is an autogenerated mock type for the TodoRepository type
type MockTodoRepository struct {
	mock.Mock
}

type MockTodoRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTodoRepository) EXPECT() *MockTodoRepository_Expecter {
	return &MockTodoRepository_Expecter{mock: &_m.Mock}
}

// CreateTodo provides a mock function with given fields: ctx, arg
func (_m *MockTodoRepository) CreateTodo(ctx context.Context, arg sqlc.CreateTodoParams) (sqlc.Todo, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateTodo")
	}

	var r0 sqlc.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.CreateTodoParams) (sqlc.Todo, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.CreateTodoParams) sqlc.Todo); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.Todo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlc.CreateTodoParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTodoRepository_CreateTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTodo'
type MockTodoRepository_CreateTodo_Call struct {
	*mock.Call
}

// CreateTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.CreateTodoParams
func (_e *MockTodoRepository_Expecter) CreateTodo(ctx interface{}, arg interface{}) *MockTodoRepository_CreateTodo_Call {
	return &MockTodoRepository_CreateTodo_Call{Call: _e.mock.On("CreateTodo", ctx, arg)}
}

func (_c *MockTodoRepository_CreateTodo_Call) Run(run func(ctx context.Context, arg sqlc.CreateTodoParams)) *MockTodoRepository_CreateTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlc.CreateTodoParams))
	})
	return _c
}

func (_c *MockTodoRepository_CreateTodo_Call) Return(_a0 sqlc.Todo, _a1 error) *MockTodoRepository_CreateTodo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTodoRepository_CreateTodo_Call) RunAndReturn(run func(context.Context, sqlc.CreateTodoParams) (sqlc.Todo, error)) *MockTodoRepository_CreateTodo_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTodo provides a mock function with given fields: ctx, arg
func (_m *MockTodoRepository) DeleteTodo(ctx context.Context, arg sqlc.DeleteTodoParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTodo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.DeleteTodoParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTodoRepository_DeleteTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTodo'
type MockTodoRepository_DeleteTodo_Call struct {
	*mock.Call
}

// DeleteTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.DeleteTodoParams
func (_e *MockTodoRepository_Expecter) DeleteTodo(ctx interface{}, arg interface{}) *MockTodoRepository_DeleteTodo_Call {
	return &MockTodoRepository_DeleteTodo_Call{Call: _e.mock.On("DeleteTodo", ctx, arg)}
}

func (_c *MockTodoRepository_DeleteTodo_Call) Run(run func(ctx context.Context, arg sqlc.DeleteTodoParams)) *MockTodoRepository_DeleteTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlc.DeleteTodoParams))
	})
	return _c
}

func (_c *MockTodoRepository_DeleteTodo_Call) Return(_a0 error) *MockTodoRepository_DeleteTodo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTodoRepository_DeleteTodo_Call) RunAndReturn(run func(context.Context, sqlc.DeleteTodoParams) error) *MockTodoRepository_DeleteTodo_Call {
	_c.Call.Return(run)
	return _c
}

// GetTodoByID provides a mock function with given fields: ctx, arg
func (_m *MockTodoRepository) GetTodoByID(ctx context.Context, arg sqlc.GetTodoByIDParams) (sqlc.Todo, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetTodoByID")
	}

	var r0 sqlc.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.GetTodoByIDParams) (sqlc.Todo, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.GetTodoByIDParams) sqlc.Todo); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.Todo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlc.GetTodoByIDParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTodoRepository_GetTodoByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTodoByID'
type MockTodoRepository_GetTodoByID_Call struct {
	*mock.Call
}

// GetTodoByID is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.GetTodoByIDParams
func (_e *MockTodoRepository_Expecter) GetTodoByID(ctx interface{}, arg interface{}) *MockTodoRepository_GetTodoByID_Call {
	return &MockTodoRepository_GetTodoByID_Call{Call: _e.mock.On("GetTodoByID", ctx, arg)}
}

func (_c *MockTodoRepository_GetTodoByID_Call) Run(run func(ctx context.Context, arg sqlc.GetTodoByIDParams)) *MockTodoRepository_GetTodoByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlc.GetTodoByIDParams))
	})
	return _c
}

func (_c *MockTodoRepository_GetTodoByID_Call) Return(_a0 sqlc.Todo, _a1 error) *MockTodoRepository_GetTodoByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTodoRepository_GetTodoByID_Call) RunAndReturn(run func(context.Context, sqlc.GetTodoByIDParams) (sqlc.Todo, error)) *MockTodoRepository_GetTodoByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListTodosByUser provides a mock function with given fields: ctx, userID
func (_m *MockTodoRepository) ListTodosByUser(ctx context.Context, userID int64) ([]sqlc.Todo, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListTodosByUser")
	}

	var r0 []sqlc.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]sqlc.Todo, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []sqlc.Todo); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTodoRepository_ListTodosByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTodosByUser'
type MockTodoRepository_ListTodosByUser_Call struct {
	*mock.Call
}

// ListTodosByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockTodoRepository_Expecter) ListTodosByUser(ctx interface{}, userID interface{}) *MockTodoRepository_ListTodosByUser_Call {
	return &MockTodoRepository_ListTodosByUser_Call{Call: _e.mock.On("ListTodosByUser", ctx, userID)}
}

func (_c *MockTodoRepository_ListTodosByUser_Call) Run(run func(ctx context.Context, userID int64)) *MockTodoRepository_ListTodosByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockTodoRepository_ListTodosByUser_Call) Return(_a0 []sqlc.Todo, _a1 error) *MockTodoRepository_ListTodosByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTodoRepository_ListTodosByUser_Call) RunAndReturn(run func(context.Context, int64) ([]sqlc.Todo, error)) *MockTodoRepository_ListTodosByUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTodo provides a mock function with given fields: ctx, arg
func (_m *MockTodoRepository) UpdateTodo(ctx context.Context, arg sqlc.UpdateTodoParams) (sqlc.Todo, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTodo")
	}

	var r0 sqlc.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.UpdateTodoParams) (sqlc.Todo, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.UpdateTodoParams) sqlc.Todo); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.Todo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlc.UpdateTodoParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTodoRepository_UpdateTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTodo'
type MockTodoRepository_UpdateTodo_Call struct {
	*mock.Call
}

// UpdateTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.UpdateTodoParams
func (_e *MockTodoRepository_Expecter) UpdateTodo(ctx interface{}, arg interface{}) *MockTodoRepository_UpdateTodo_Call {
	return &MockTodoRepository_UpdateTodo_Call{Call: _e.mock.On("UpdateTodo", ctx, arg)}
}

func (_c *MockTodoRepository_UpdateTodo_Call) Run(run func(ctx context.Context, arg sqlc.UpdateTodoParams)) *MockTodoRepository_UpdateTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlc.UpdateTodoParams))
	})
	return _c
}

func (_c *MockTodoRepository_UpdateTodo_Call) Return(_a0 sqlc.Todo, _a1 error) *MockTodoRepository_UpdateTodo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTodoRepository_UpdateTodo_Call) RunAndReturn(run func(context.Context, sqlc.UpdateTodoParams) (sqlc.Todo, error)) *MockTodoRepository_UpdateTodo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTodoRepository creates a new instance of MockTodoRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTodoRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTodoRepository {
	mock := &MockTodoRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
